title: Sarder Rafee Musabbir # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Ph.D. candidate with a formal background in transportation engineering. 
  Though my current research follows Autonomous Vehicles and dynamic games, my varied experience has allowed the learning of various aspects of transportation, including traffic operation and control, travel demand management, and Machine Learning & Data Analytics. 
  During my training, I have had exposure to different softwares (e.g. SUMO, Carla, TRANSCAD, VISSIM, ArcGIS) and programming languages (e.g. MATLAB, R, Python, Julia), which helped me to model the problems in the data-centric intelligent transportation system. 
  Now, I want to engage myself in a creative and efficient setting while nurturing a synergy between technology and practical solutions. 
  Within the storm of initiatives and emerging technologies in transportation, I feel the holistic approach involving communities, empirical findings, and sustainable technologies is a pathway for the betterment of society. 
  <br><br>
  <a href="https://scholar.google.com/citations?user=sCYZ9AsAAAAJ&hl=en">View My Google Scholar Profile</a> 
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/sarder-rafee-musabbir-95446a73/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 223589850 # your Google Analytics tracking ID here
