title: Sarder Rafee Musabbir # your name (or website title) here
logo: "/images/2_Right-turn_Conflict-Point.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Ph.D. candidate @UC Davis with a formal background in transportation engineering. 
  My current research follows Autonomous Vehicles, Dynamic Games, Scientific Machine Learning, and Bayesian Modeling. 
  My varied experience in transportation has allowed the learning of various aspects of transportation, including traffic operation and control, traffic simulation, Safety Modeling. 
  During my training, I have had exposure to different softwares (e.g. SUMO, Carla, TRANSCAD, VISSIM, ArcGIS) and programming languages (e.g. Julia, R, Python, MATLAB), which helped me to model the problems in the data-centric intelligent transportation system.   <br><br>
  <a href="https://scholar.google.com/citations?user=sCYZ9AsAAAAJ&hl=en">View My Google Scholar Profile</a> 
  <br>
  <a href="https://www.linkedin.com/in/sarder-rafee-musabbir-95446a73/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 223589850 # your Google Analytics tracking ID here
